### ISSUE TITLE
mountConflictDelay: Host entry (with one volume exported) is not wiped out from 3par array after cleaning-up of VLUN forcefully.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#153]
Steps to reproduce:

1. On fresh setup, create a volume and mount it to a container1 in node1.
2. Mount the same volume to container2 in node2.
3. Wait for 30 seconds (default mountConflictDelay period).
4. Observe VLUNs get cleaned up from node1 and 3par array.
5. Host entry is still there for node1 in 3par array. This would possibly hit the Issue #58

**Comment by imran-ansari** [comment]
This has been fixed. Code under. Review.

**Comment by sonawane-shashikant** [comment]
On multinode docker, having 2 plugin nodes, pointing to the common etcd node, this issue is fixed.
Below is the detailed output for the same.

WORKER-1 - BEFORE
docker@cld6b5:~$ docker plugin inspect hpe | grep PluginRef
        "PluginReference": "docker.io/hpestorage/hpedockervolumeplugin:2.1",
docker@cld6b5:~$


docker@cld6b5:~$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          SNAP
hpe:latest          VOL
docker@cld6b5:~$ docker inspect VOL
[
    {
        "Driver": "hpe:latest",
        "Labels": null,
        "Mountpoint": "/opt/hpe/data/hpedocker-dm-uuid-mpath-360002ac0000000000100c96200019d52",
        "Name": "VOL",
        "Options": {},
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "compression": null,
                "flash_cache": null,
                "mountConflictDelay": 30,
                "provisioning": "full",
                "size": 17
            }
        }
    }
]
docker@cld6b5:~$ ls -lrt /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part5 -> ../../sda5
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root  9 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:1 -> ../../sdb
lrwxrwxrwx 1 root root  9 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx 1 root root  9 Apr  3 23:18 pci-0000:21:00.2-fc-0x20010002ac019d52-lun-0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Apr  3 23:18 pci-0000:21:00.3-fc-0x20020002ac019d52-lun-0 -> ../../sdd
docker@cld6b5:~$ docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
a72b6d75a60b        busybox             "/bin/sh"           2 hours ago         Up 2 hours                              MOUNT1
docker@cld6b5:~$

WORKER-2-BEFORE
docker@cld6b4:~$ docker plugin inspect hpe | grep PluginRef
        "PluginReference": "docker.io/hpestorage/hpedockervolumeplugin:2.1",
docker@cld6b4:~$

docker@cld6b4:~$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          SNAP
hpe:latest          VOL
docker@cld6b4:~$ docker inspect VOL
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/opt/hpe/data/hpedocker-dm-uuid-mpath-360002ac0000000000100c96200019d52",
        "Name": "VOL",
        "Options": {
            "provisioning": "full",
            "size": "17"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "compression": null,
                "flash_cache": null,
                "mountConflictDelay": 30,
                "provisioning": "full",
                "size": 17
            }
        }
    }
]

docker@cld6b4:~$ ls -lrt /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:1-part1 -> ../../sdb1
lrwxrwxrwx 1 root root  9 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:1 -> ../../sdb
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:2-part1 -> ../../sdc1
lrwxrwxrwx 1 root root  9 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:2 -> ../../sdc
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part5 -> ../../sda5
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root  9 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0 -> ../../sda
docker@cld6b4:~$


ARRAY - BEFORE MIGRATION

CSIM-8K02_MXN6072AC7 cli% showvv -cpg SHASHI-SSD
                                                                                        -Rsvd(MiB)- -(MiB)-
   Id Name                       Prov Compr Dedup Type CopyOf  BsId Rd -Detailed_State-  Snp    Usr   VSize
51556 dcv-Q87H3EOqQmGlNwTwpjCTug tpvv No    No    base ---    51556 RW normal           1024   1024  102400
51554 dcv-Rymb600ySNaVhuwz0TXamg cpvv NA    NA    base ---    51554 RW normal           1024  17408   17408
-----------------------------------------------------------------------------------------------------------
    2 total                                                                             2048  18432  119808
CSIM-8K02_MXN6072AC7 cli% showvv -cpg SS_CPG6
                                                                                        -Rsvd(MiB)- -(MiB)-
   Id Name                       Prov Compr Dedup Type CopyOf  BsId Rd -Detailed_State-  Snp    Usr   VSize
51556 dcv-Q87H3EOqQmGlNwTwpjCTug tpvv No    No    base ---    51556 RW normal           1024   1024  102400
51554 dcv-Rymb600ySNaVhuwz0TXamg cpvv NA    NA    base ---    51554 RW normal           1024  17408   17408
-----------------------------------------------------------------------------------------------------------
    2 total                                                                             2048  18432  119808
CSIM-8K02_MXN6072AC7 cli% showvlun -host cld6b4
Active VLUNs
Invalid host name: cld6b4
CSIM-8K02_MXN6072AC7 cli% showvlun -host cld6b5
Active VLUNs
Lun VVName                     HostName -Host_WWN/iSCSI_Name-  Port        Type Status ID
  0 dcv-Rymb600ySNaVhuwz0TXamg cld6b5   100038EAA730E421      0:0:1 matched set active  1
  0 dcv-Rymb600ySNaVhuwz0TXamg cld6b5   100038EAA730E425      0:0:2 matched set active  1
-----------------------------------------------------------------------------------------
  2 total

VLUN Templates
Lun VVName                     HostName -Host_WWN/iSCSI_Name-  Port        Type
  0 dcv-Rymb600ySNaVhuwz0TXamg cld6b5   ----------------      0:0:1 matched set
  0 dcv-Rymb600ySNaVhuwz0TXamg cld6b5   ----------------      0:0:2 matched set
-------------------------------------------------------------------------------
  2 total

CSIM-8K02_MXN6072AC7 cli% showhost cld6b5
Id Name   Persona      -WWN/iSCSI_Name- Port
26 cld6b5 Generic-ALUA 100038EAA730E421 0:0:1
                       100038EAA730E425 0:0:2
---------------------------------------------
 2 total
CSIM-8K02_MXN6072AC7 cli%


WORKER-2 - AFTER MIGRATION

docker@cld6b4:~$ docker run -it -d --mount src=VOL,dst=/data1,volume-driver=hpe --name MOUNT --rm busybox /bin/sh
be559d21d131b35d6c0749c7efb7dc255c8416082501c6176700460f6aeb4f3e
docker@cld6b4:~$ ls -lrt /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:1-part1 -> ../../sdb1
lrwxrwxrwx 1 root root  9 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:1 -> ../../sdb
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:2-part1 -> ../../sdc1
lrwxrwxrwx 1 root root  9 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:2 -> ../../sdc
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part5 -> ../../sda5
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root  9 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx 1 root root  9 Apr  4 02:14 pci-0000:21:00.2-fc-0x20010002ac019d52-lun-0 -> ../../sdd
lrwxrwxrwx 1 root root  9 Apr  4 02:14 pci-0000:21:00.3-fc-0x20020002ac019d52-lun-0 -> ../../sde
docker@cld6b4:~$

ON ARRAY - 

CSIM-8K02_MXN6072AC7 cli% showhost cld6b5
no hosts listed
CSIM-8K02_MXN6072AC7 cli% showhost cld6b4
Id Name   Persona      -WWN/iSCSI_Name- Port
28 cld6b4 Generic-ALUA 100038EAA730E429 0:0:1
                       100038EAA730E42D 0:0:2
---------------------------------------------
 2 total
CSIM-8K02_MXN6072AC7 cli%


WORKER-1-AFTER MIGRATION

docker@cld6b5:~$ docker run -it -d --^Cunt src=VOL,dst=/data1,volume-driver=hpe --name MOUNT1 --rm busybox /bin/sh
docker@cld6b5:~$ docker attach MOUNT1
/ # exit
docker@cld6b5:~$ ls -lrt /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part5 -> ../../sda5
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root 10 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root  9 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:1 -> ../../sdb
lrwxrwxrwx 1 root root  9 Apr  3 20:47 pci-0000:03:00.0-scsi-0:1:0:0 -> ../../sda
docker@cld6b5:~$

**Comment by sumitshatwara** [comment]
Verified in the latest build: hpestorage/hpedockervolumeplugin:2.1 with plain docker as well as OpenShift platform and observed it was fixed.
