### ISSUE TITLE
Kubernetes : Pod goes in containerCreating state when pv is created with cloneOf option. (K8s 1.8)

### ISSUE THREAD

**Issue by atotala** [hpe-storage/python-hpedockerplugin#173]
Environment:
OS: RHEL 7.4
Docker version: 17.06
K8s version: 1.8.9
HPE Plugin: Legacy volume plugin 2.1
Step to reproduce:
1.	Create PV1 with provisioning=dedup, flash-cache=true, compression=true and qos-name=myvvs.
2.	Create PVC1.
3.	Create Pod1 with PVC1 (Mount 3par volume to Pod)
4.	Ensure that volume is created and mounted successfully.
5.	Create PV2 with cloneOf=PV1.
6.	Create PVC which is bound to PV2
7.	Create Pod2 with PVC
8.	Verify the pod2 creation using “kubectl describe pod pod2” command
Failure is seen as follows:
Warning  FailedMount            1m (x9 over 3m)  kubelet, cld6b16   MountVolume.SetUp failed for volume "pv2" : mount command failed, status: Failure, reason: invalid character '<' looking for beginning of value

Detailed output of every step and dory.log are attached.
[console_output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1927406/console_output.txt)
[dory_log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1927407/dory_log.txt)

Note: Volume is getting created successfully on 3PAR and docker host, only mounting is getting failed.

**Comment by imran-ansari** [comment]
@atotala - Please attach HPE Docker Plugin logs as well.

**Comment by atotala** [comment]
The fix for the issue is verified. Attaching the result for the same.
[test_result_173.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1949638/test_result_173.txt)

**Comment by imran-ansari** [comment]
Just for records - here is what was happening:

There are two different exceptions happening here – 
1.	At the first mount attempt, 
2.	On subsequent mounts (caused due to the first one)

After cloning using online-copy, we are immediately firing mount, and during that time, the clone is yet to transition to a physical copy, the corresponding 3PAR volume object doesn’t have all its properties set that we would usually get when we fetch a volume. In this case, the properties in question are “userCPG” and “snapCPG” that are needed to get the domain so that that domain could be used to create host. So, the code fetches the volume (on which online copy is still running) and tries to access the CPG field and there it encounters first exception. But by this time, node_mount_info is already updated in ETCD (this needs to fixed either by moving the update part later in the flow or have rollback mechanism). Please note that path_info is not updated in the flow yet and an exception has occurred. So path_info will remain null.

Now when next mount request comes in, it finds node_mount_info already there. So it assumes that the volume is mounted and all it needs to do is to fetch Docker volume and read path_info etc and return it as JSON object. However, since null path_info is returned in JSON, JSON fails to load that string and results into the following exception:

>>> json.loads(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

Since, only one CPG is supported at the moment in Docker, rather than getting the CPG name from 3PAR volume object, we can read it from the configuration file to fix this.
