### ISSUE TITLE
Add secrets support to store storage credentials

### ISSUE THREAD

**Issue by garthmbooth** [hpe-storage/python-hpedockerplugin#22]
Now that Docker 1.13 supports secrets, we should move the credential information currently stored in the hpe.conf file to secrets.

**Comment by prablr79** [comment]
Current Docker volume plugin 3.0 is designed and developed hpe3par encryption utility which will be used as to store 3par credentials in encrypted format, we are not consuming any of the Docker secrete management utility. the purpose is achieved since 3par Plugin will be container provider agnostic.  Hence closing this defect.
