### ISSUE TITLE
Multi-array: key ssh_hosts_key_file is needed for every backend

### ISSUE THREAD

**Issue by wdurairaj** [hpe-storage/python-hpedockerplugin#254]
Right now the code looks for `ssh_hosts_key_file` in every backend if more than 1 backend is specified.

Ideally, it should read that information as part of the DEFAULT section and read from that.

**Comment by imran-ansari** [comment]
ssh_hosts_key_file has been defined as part of hpe3par_opts (driver specific options - now backend options), instead of setupcfg.host_opts. This can be addressed by segregating host options as separate oslo_config object, called host_config, which can be passed to the VolumePlugin and other objects that need it in addition to backend configurations that we are passing.

@wdurairaj - can you please assign this to me?

**Comment by sonawane-shashikant** [comment]
VERIFIED this issues as FIXED.

[ssh-verification-terminal.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2352214/ssh-verification-terminal.txt)
