### ISSUE TITLE
Cloning of full provisioning volume via offline copy failed

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#326]
Manage: The clone of the import volume failed at docker after changing the size with multi-cpg option. But clone gets created at backend 3par.

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker version: Version:17.06.2-ee-16
3PAR array: 192.168.67.7 [DEFAULT],15.212.192.252[3par1] 192.168.67.2 [3par11]

1) Create a volume at backend 3par1 array
     createvv Sandesh VOLUME 100g
2)  Manage the volume at docker
     docker volume create -d hpe --name=Test -o importVol=VOLUME -o backend=3par1
3)  Create a clone with size=200g and with multi-cpg option
     docker volume create -d hpe --name=Test_clone -o cloneOf=Test -o size=200 -o cpg=Sandesh
 
   Clone gets created at backend 3par1 array successfully.But on docker host it failed with the below error:

docker volume create -d hpe --name=Test_clone -o cloneOf=Test -o size=200 -o cpg=Sandesh
**"Error response from daemon: create Test_clone: Post http://%2Frun%2Fdocker%2Fplugins%2Fb5f9bdb3596bf01b4acc99e11978b61910292764d2834b0b907c5fe8c45af9f5%2Fhpe.sock/VolumeDriver.Create: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"**
    
Attaching Syslog,hpe.confand docker,3par1 ouput
[docker and 3par ouput.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2374308/docker.and.3par.ouput.txt)
[Hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2374309/Hpe.conf.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2374311/Syslog.txt)

**Comment by sonivi** [comment]
This issue is not specific to manage feature, its producible while cloning plain docker volume with provisioning **full** also.

since the source and destination volume size is different, code takes offline copy path and waits for the task completion. And its taking around 15 mins to copy, docker timeout.

**clone of thin volume task**:
CB2515_2000K_252 cli% showtask -d 3973
  Id Type    Name                                                   Status Phase Step -------StartTime------- ------FinishTime------- -Priority- -User--
3973 vv_copy dcv-j9nMirUgQN2iMJ.CcA-y.g->dcv-v7ICVoN1RJe1lU4blAeMeA done     ---  --- _2018-09-17 14:25:46 IST 2018-09-17 14:25:46_ IST high       3paradm


**clone of full volume task**:
CB2515_2000K_252 cli% showtask -d 3971
  Id Type    Name                                                   Status Phase Step -------StartTime------- ------FinishTime------- -Priority- -User--
3971 vv_copy dcv-4YgZrlVlTH2OJS.tB3nCwQ->dcv-oOIFMrBnSB6RXVkSK8Zwzw done     ---  --- _2018-09-17 14:08:43 IST 2018-09-17 14:23:04_ IST high       3paradm

[thin_vv_clone.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2388432/thin_vv_clone.txt)
[full_vv_clone_old.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2388433/full_vv_clone_old.txt)

**Comment by sonivi** [comment]
Keeping docker on hold till the 3PAR offline copy task to get completed, will always results in failure in docker env.
I suggest we can remove the code to wait for offline copy to complete.
To support my suggestion, other 3PAR related tool like imc, also does not wait for this process and displays volume and in 3PAR background, process still goes on
@wdurairaj , @prablr79  please suggest your thoughts

**Comment by imran-ansari** [comment]
Would suggest maintaining volume state at this juncture e.g. CREATING in this case and let the clone return immediately after starting offline copy.
When user tries to perform any operation including inspect on this volume and if it is not in AVAILABLE state, then let the plugin ask 3PAR if the task is still in progress or it's complete and accordingly process the request.

**Comment by sonivi** [comment]
As discussed, we will remove the wait code in offline copy workflow and go with inserting a code to check any active task on that particular volume at create_volume() to avoid any subsequent operation like snapshot and clone creation.

we can store the STATE of volume in future and will take that as enhancement

**Comment by sonawane-shashikant** [comment]
This issue is verified as FIXED.

Attached is the detailed output and relevant log.


[Issue326Fix.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2433592/Issue326Fix.txt)

[issue326WithOfflineCopy.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2433597/issue326WithOfflineCopy.txt)

@sandesh-desai Please close this issue

**Comment by sandesh-desai** [comment]
Closed the BUG after verifying above output.
