### ISSUE TITLE
PVC not coming in bound state for -o import vol option

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#481]
Getting volume size error despite not using size option in sc.yml, though use size option in sc getting similar issue.

Steps performed:
===========
[root@master-node-1 STORAGE-CLASS]# kubectl create -f sc1-importvol.yaml
storageclass.storage.k8s.io/sc1-importvol-1 created
[root@master-node-1 STORAGE-CLASS]# kubectl create -f pvc-importvol.yaml
persistentvolumeclaim/pvc1-importvol-1 created
[root@master-node-1 STORAGE-CLASS]# kubectl get sc,pvc
NAME                                          PROVISIONER   AGE
storageclass.storage.k8s.io/sc1-importvol-1   hpe.com/hpe   19s

NAME                                     STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS      AGE
persistentvolumeclaim/pvc1-importvol-1   Pending                                      sc1-importvol-1   10s

vi sc1-importvol.yaml
=====================

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
 name: sc1-importvol-1
provisioner: hpe.com/hpe
parameters:
  importVol: TEST_VOL
  backend: 3PAR1

vi pvc-importvol.yaml
==============
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc1-importvol-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc1-importvol-1

find attached log for the same.
[import_vol issue.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2875295/import_vol.issue.txt)

**Comment by prablr79** [comment]
@virendra-sharma is this visible in 3.0 release as well ? get a chance to check the 3.0 release build ?

**Comment by wdurairaj** [comment]
`importVol` is not a right parameter to use in a storage class , since during a dynamic volume creation, the same importVol option will triggered with the same volume (which was used in the first import) will be attempted and the second volume creation onwards will fail.

This is because, the first volume creation will rename the vol to a `dcv-` prefix, and the original volume no more exists.

- If another volume create with -o importVol is performed with the parameter value as original volume name, it no more exists and an error will be thrown, which will make PVC in Pending state.

This is not a bug in my view.

**Comment by nilangekarss** [comment]
@virendra-sharma We allowed size parameter to be passed for creating a snapshot. This was done because, dory passes size information irrespective of user passes it or not.

```
https://github.com/hpe-storage/python-hpedockerplugin/commit/41d2bcc1eebe03aecfa64d86c18ff3baec86a8e3#diff-36ee397872b9649d4a6ee0be011f6473

```

But in our validations (from docker perspective and from the angle of import) size should not be allowed while importing the volume to docker environment.

Due the dory and k8s restriction we need to allow size parameter while importing volume and need to be validated with volume being imported. If the size of volume to be imported does not match with the size of  storage in PVC import should fail, else import should be successful.


```
https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/hpedockerplugin/request_validator.py#L115

```

**Comment by nilangekarss** [comment]
@virendra-sharma @wdurairaj i Agree with William's points... A StorageClass provides a way for administrators to describe the “classes” of storage they offer. Administrator can not use same StorageClass for importing volumes.

**Comment by prablr79** [comment]
@virendra-sharma can you recheck and close this bug ?

**Comment by prablr79** [comment]
Lets document Swapnil clarity in Readme or Kubernetes BPG

**Comment by virendra-sharma** [comment]
Clarity provided by @wdurairaj , hence closing this bug.
