### ISSUE TITLE
Green Field install  doryd service fails to start 

### ISSUE THREAD

**Issue by Acidguy** [hpe-storage/python-hpedockerplugin#521]
[root@oshift-fc-m1 python-hpedockerplugin]# systemctl status doryd
● doryd.service - manage doryd service for HPE 3PAR Volume plugin for Docker
   Loaded: loaded (/etc/systemd/system/doryd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-03-22 05:33:20 EDT; 37s ago
  Process: 26453 ExecStart=/usr/libexec/kubernetes/kubelet-plugins/volume/exec/hpe.com~hpe/doryd /etc/kubernetes/admin.conf hpe.com (code=exited, status=1/FAILURE)
 Main PID: 26453 (code=exited, status=1/FAILURE)

Mar 22 05:33:20 oshift-fc-m1.tennet.local systemd[1]: Started manage doryd service for HPE 3PAR Volume plugin for Docker.
Mar 22 05:33:20 oshift-fc-m1.tennet.local doryd[26453]: Error getting config from file /etc/kubernetes/admin.conf - stat /etc/kubernetes/admin.conf:...irectory
Mar 22 05:33:20 oshift-fc-m1.tennet.local doryd[26453]: Error getting config cluster - unable to load in-cluster configuration, KUBERNETES_SERVICE_H... defined
Mar 22 05:33:20 oshift-fc-m1.tennet.local systemd[1]: doryd.service: main process exited, code=exited, status=1/FAILURE
Mar 22 05:33:20 oshift-fc-m1.tennet.local systemd[1]: Unit doryd.service entered failed state.
Mar 22 05:33:20 oshift-fc-m1.tennet.local systemd[1]: doryd.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@oshift-fc-m1 python-hpedockerplugin]# ps -ef | grep dory
root      27110  99091  0 05:34 pts/3    00:00:00 grep --color=auto dory

Openshift version 3.10 
multi-master environment

**Comment by farhan7500** [comment]
Verified the defect,

[root@cssosbe04-b01 ansible_3par_docker_plugin]# service doryd status
Redirecting to /bin/systemctl status doryd.service
● doryd.service - manage doryd service for HPE 3PAR Volume plugin for Docker
   Loaded: loaded (/etc/systemd/system/doryd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-03-22 15:41:33 IST; 7s ago
  Process: 2014 ExecStart=/usr/libexec/kubernetes/kubelet-plugins/volume/exec/hpe.com~hpe/doryd /etc/kubernetes/admin.conf hpe.com (code=exited, status=1/FAILURE)
 Main PID: 2014 (code=exited, status=1/FAILURE)

Mar 22 15:41:33 cssosbe04-b01 systemd[1]: Started manage doryd service for HPE 3PAR Volume plugin for Docker.
Mar 22 15:41:33 cssosbe04-b01 doryd[2014]: Error getting config from file /etc/kubernetes/admin.conf - stat /etc/kubernetes/admin.conf: no such file or directory
Mar 22 15:41:33 cssosbe04-b01 doryd[2014]: Error getting config cluster - unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
Mar 22 15:41:33 cssosbe04-b01 systemd[1]: doryd.service: main process exited, code=exited, status=1/FAILURE
Mar 22 15:41:33 cssosbe04-b01 systemd[1]: Unit doryd.service entered failed state.
Mar 22 15:41:33 cssosbe04-b01 systemd[1]: doryd.service failed.

**Comment by farhan7500** [comment]
Fixed! in https://github.com/hpe-storage/python-hpedockerplugin/pull/522

[root@cssosbe04-b01 ansible_3par_docker_plugin]# service doryd status
Redirecting to /bin/systemctl status doryd.service
● doryd.service - manage doryd service for HPE 3PAR Volume plugin for Docker
   Loaded: loaded (/etc/systemd/system/doryd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2019-03-22 15:46:00 IST; 9s ago
 Main PID: 13140 (doryd)
    Tasks: 20
   Memory: 7.3M
   CGroup: /system.slice/doryd.service
           └─13140 /usr/libexec/kubernetes/kubelet-plugins/volume/exec/hpe.com~hpe/doryd /etc/kubernetes/admin.conf hpe.com

Mar 22 15:46:00 cssosbe04-b01 systemd[1]: Started manage doryd service for HPE 3PAR Volume plugin for Docker.
Mar 22 15:46:00 cssosbe04-b01 doryd[13140]: 15:46:00 provisioner.go:184: provisioner (prefix=hpe.com) is being created with instance id 13ae4762-9562-4c8e-8211-8fa2cea18703.
Mar 22 15:46:05 cssosbe04-b01 doryd[13140]: 15:46:05 provisioner.go:237: statusLogger: provision chains=0, delete chains=0, parked chains=0, ids tracked=0, connection=valid

**Comment by farhan7500** [comment]
@Acidguy Pleasecould you verify the fix.

**Comment by Acidguy** [comment]
issue resolved thanks
