### ISSUE TITLE
file storage configuration not validated properly

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#605]
```docker volume create -d hpe --name test1 -o help=backend -o filePersona``` command return output as DEFAULT_FILE=OK.
whereas snapcpg mentioned in file storage configuration.

**Comment by imran-ansari** [comment]
@prablr79 , @wdurairaj , @nilangekarss 
This is about mixing configuration parameters of file and block in the same backend section.
E.g. in a File driver backend, user specifies block specific parameters as well like snapcpg, replication etc and vice-versa..

In this case, the parameters that are not applicable to the configured driver are ignored as these are harmless.

I'm inclined to mark this as documentation issue rather than fixing it in code by putting checks for those parameters that have absolutely no impact on the functioning of the driver. Validation would have been required if those parameters had any negative effect on the driver.

Please let me know what's your take on this?

**Comment by nilangekarss** [comment]
@virendra-sharma 
As Imran pointed out it will only allow valid volume/persona option to be set in configuration file.
If few of unsupported options are passed to file share creations these will be simply ignored by plugin .
Same is the case of volume creations as well. This will not impact any functionality.

This can be documented with an example and this can be marked as documentation issue.
Please provide your comments on same.

**Comment by imran-ansari** [comment]
@virendra-sharma - kindly let us know your thoughts on making this as a documentation issue.

**Comment by virendra-sharma** [comment]
@imran-ansari due to time constraint we can document this for this release, but will need to take it as enhancement for next release.

**Comment by imran-ansari** [comment]
Why is this high when it is harmless to specify Block configuration parameters under File backend section and vice-versa?

I would put this at low severity.

**Comment by prablr79** [comment]
Reducing it to medium since this only document changes

**Comment by prablr79** [comment]
https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/docs/share_usage.md updated link..

**Comment by virendra-sharma** [comment]
Documentation updated with known issue, Hence closing this bug.

<img width="667" alt="Documentation verification" src="https://user-images.githubusercontent.com/42762319/60718239-c5b25480-9f41-11e9-8e82-70b02e025c3e.PNG">
