### ISSUE TITLE
File persona: last share delete fpg without checking share from other host

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#610]
**Observation:** 
Last share deleted deafult fpg(DockerFpg_0) without checking existing share from different host, which used fpg (DockerFpg_0) as legacy fpg.

**Steps Performed:**
1) Create share with default fpg on host1 
Host1 --> (docker volume create -d hpe --name share01 -o filePersona)
2) Created share with legacy fpg on host2
Host2 --> (docker volume create -d hpe --name share02 -o DockerFpg_0 -o filePersona)
3) Create share with default fpg on host1 
Host1 --> (docker volume create -d hpe --name share03 -o filePersona)
4) Remove shares from host1
Host1 --> (docker volume rm share01, docker volume rm share03)
5) check fpg on 3par, it will be removed without checking existence of "share02" from "host2".

**Expectation:**
1) Host1 deleting shares not fpg so plugin should validate all shares in fpg, before deleting fpg.
2) In above case share2 was present from host2 so after removal of host1 shares, fpg must be present with share02.

**Comment by imran-ansari** [comment]
This use case brings up few points that we need to clear up to conclude how to address this:
1. FPG was created by Docker Host1 (with its own ETCD) and when there are no shares, shouldn't the owner be allowed to delete the share?
2. Share created by Docker Host2 on existing FPG not managed by Host2 is treated as legacy FPG even if it is manged by Host1. In such a case, if the FPG is not deleted by Host1 with last share delete, then that FPG goes out of Host1's radar - i.e. no more manageable by Host1.
3. If Host2 is allowed to delete FPG with last share delete, then will this same logic be applicable to the real legacy FPG too? i.e. delete it too when last Docker share is deleted on it? Can we delete something that we do not own? If not, we are contradicting ourselves in this use case being discussed - i.e. asking for a Docker FPG created by other host to be allowed to be deleted by some other host.
4. If we allow deletion of FPG without any shares, then allow it to delete the real legacy FPG too when last share on it is deleted. Otherwise, we will have to mark the FPG with something to differentiate between legacy FPG and Docker FPG which I think won't be foolproof.

@wdurairaj , @prablr79 , @nilangekarss - Please provide your comments how you think we can deal with this.

**Comment by imran-ansari** [comment]
@prablr79 - we need to finalize the approach to deal with this issue.

**Comment by sandesh-desai** [comment]
Closing this issue as FIXED.
Attaching the logs.
[Docker and 3PAR output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3230887/Docker.and.3PAR.output.txt)

@virendra-sharma : Please close this bug.

**Comment by virendra-sharma** [comment]
Closing with reference of above comment.
