### ISSUE TITLE
File Persona: Share creation in an incorrect FPG

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#653]
File Persona: Share creation in an incorrect FPG 

Testbed Details:
Host:192.168.68.31
Host OS: "SUSE Linux Enterprise Server 12 SP3"
Docker Version: 17.06.2-ee-20
3PAR array: 192.168.67.6 [DEFAULT] & [3PAR]

Steps perform:
1) Hpe.conf have "DEFAULT" and Additional backend as "3PAR".Both have same configuration.
2) Create share1 and share2 by using additional backend as "3PAR" 
3) Create share3 by using "DEFAULT"
4) When inspect share3, it created successfully with cpg mention in hpe.conf but it belongs to the different fpg.

Attaching the logs:
[Docker logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3289928/Docker.logs.txt)
[Hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3289929/Hpe.conf.txt)
[Messages file.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3289930/Messages.file.txt)
[3PAR logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3289931/3PAR.logs.txt)

**Comment by imran-ansari** [comment]
This is an expected behavior - despite pointing to the same array, these are two different backends, hence the default FPG names won't be shared by them and this is by design.
It is expected that for File driver, there will always be one and only one backend entry in the configuration file for a given array.
However, if the user still insists on having different backend entries for a given array then at best we can document this.
@prablr79 - In my opinion, we can mark this as a documentation issue for the above said reasons as this is not a regular use case.

**Comment by prablr79** [comment]
since it is documentation issue, hence reducing to Medium

**Comment by sandesh-desai** [comment]
As per below statement mention in help document closing the bug.
**"Although HPE does not recommend it, but if the user configures multiple backends that are identical in terms of target array and CPG, then the default FPG created for such backends would not be the same – rather a different default FPG would be created for each backend."**
